openapi: 3.0.2
servers:
  - url: 'https://esignsante.psc.esante.gouv.fr/v1'
    description: Sandbox
info:
  title: eSignSantePSC
  version: '1.0'
  description: 'Public API for document digital signature'
tags:
  - name: utils
  - name: signature
  - name: checksignature 
paths:
  /:
    get:
      summary: Your GET endpoint
      tags: 
      - utils
      responses:
        '200':
          description: Requête en succès.
          content:
            application/json:
              schema:
                type: array
                description: ''
                minItems: 1
                uniqueItems: true 
                items: 
                  $ref: '#/components/schemas/Operation'
              examples:
                example-1:
                  value:
                    - path: /
                      description: Liste des opérations disponibles
                    - path: /asksignsature/xades
                      description: signe un document XML à la norme Xades
                    - path: /asksignsature/pades
                      description: signe un document PDF à la norme Pades
                      body: fichier à signer....              
        '400':
          description: Requête mal formée.
        '500':
          description: Erreur interne du serveur.
      operationId: get-operations
      description: 'Opération qui permet au client de lister les opérations offertes par le composant eSignSante-PSC.  '
components:
  schemas:
    Operation:
      title: Operation
      type: object
      properties:
        path:
          type: string
        description:
          type: string
        payload:
          type: string
        requiredHeaders:
          type: string
  securitySchemes:
    PRO-SanteConnect:
      type: openIdConnect
      openIdConnectUrl: 'https://auth.esw.esante.gouv.fr/auth/realms/esante-wallet/.well-known/wallet-openid-configuration'
    Pro-SanteConnect_BAS:
      type: openIdConnect
      openIdConnectUrl: 'https://auth.bas.esw.esante.gouv.fr/auth/realms/esante-wallet/.well-known/wallet-openid-configuration'
