openapi: 3.0.2
# Added by API Auto Mocking Plugin
servers:
-  description: SwaggerHub API Auto Mocking
   url: https://esignsante-psc.sign.ans.fr{basePath}/
   variables:
      port:
         enum:
         - '8080'
         default: '8080'
      basePath:
         default: /
info:
   description: TODO API esignsante-psc API du composant eSignSante-psc....
   version: 1.0.0.0
   title: eSignSantePSC
   contact:
      email: esignsante@asipsante.fr
tags:
-  name: client
   description: Ressources offertes au client.
-  name: testsign
   description: POST pour test tehnique .

paths:
   /:
      get:
         summary: Liste des opérations disponibles.
         operationId: getOperations
         description: "Opération ... le composant ANS esignsante-psc. "
         tags:
         - client
         responses:
            '200':
               description: Requête en succès.
               content:
                  application/json:
                     schema:
                        type: array
                        items:
                           type: string
            '400':
               description: Requête mal formée.
            '500':
               description: Erreur interne du serveur.

   /signature/test:
      post:
         summary: demande de signature de PSC.
         operationId: signeDocument
         description: "Pour test fonctionnement du composant (datas IN et OUT). Simule un post reçu de PSC pour une demande de signature. "
         tags:
         - testsign
         requestBody:
            content:
               application/json:
                  schema:
                     $ref: '#/components/schemas/RequeteSignatureRecue'
         responses:
            '200':
               description: Requête en succès.
               content:
                  application/json:
                     schema:
                        type: object
                        $ref: '#/components/schemas/ReponseDocumentSigne'
            '201':
               description: Token non confirmé par PSC. Requête refusée.
            '400':
               description: Erreur sur les paramètres reçus en entrée.
            '500':
               description: Erreur interne du serveur.
components:
   schemas:
      RequeteSignatureRecue:
         type: object
         description: Demande de signature reçue
         required:
         - token
         - documentASigner
         properties:
            token:
               description: token PSC transmis
               type: string
            documentASigner:
               description: document à signer reçu de PSC 
               type: string
      ReponseDocumentSigne:
         type: object
         description: Document signer par PSC
         required:
         - idMongoDB
         - documentSigne
         properties:
            idMongoDB:
               description: identifiant de la sauveagrde de la preuve
               type: string
            documentSigne:
               description: document signé par esignsante à renvoyer au client
               type: string